import Client from "../client";
import events from "../events";

export type WithRes<T> = [body: T, res: Response];

type Method = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export async function req(
	method: Method,
	path: string,
	c: Client,
	body?: Record<string, unknown>,
	refreshed = false
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
): Promise<Response> {
	const url = c.settings.root + path;
	const res = await window.fetch(url, {
		method,
		// eslint-disable-next-line @typescript-eslint/no-explicit-any
		body: JSON.stringify(body),
		headers: {
			"Content-Type": "application/json",
			"User-Agent": c.settings.userAgent || navigator.userAgent,
			// eslint-disable-next-line @typescript-eslint/no-explicit-any
		} as any,
		credentials: "include",
	});
	if (
		res.status === 401 &&
		path !== "/auth/login" &&
		path !== "/auth/refresh"
	) {
		if (!refreshed) {
			await c._refreshToken();
			return req(method, path, c, body, true);
		} else {
			// Emit the fact that user is logged out
			events.emit("unauthorized");
		}
	}
	return res;
}

const dateRegex =
	/^(\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d\.\d+([+-][0-2]\d:[0-5]\d|Z))|(\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d([+-][0-2]\d:[0-5]\d|Z))|(\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d([+-][0-2]\d:[0-5]\d|Z))$/;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function parseJSON(str: string): any {
	return JSON.parse(str, (key, val: unknown) => {
		if (typeof val === "string" && dateRegex.test(val)) return new Date(val);
		else return val;
	});
}

// eslint-disable-next-line @typescript-eslint/ban-types
export function removeDates<T extends object>(obj: T): NoDates<T> {
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	const newObj: any = Array.isArray(obj) ? [] : {};
	for (const [key, val] of Object.entries(obj)) {
		if (val instanceof Date) newObj[key] = val.toISOString();
		else if (typeof val === "object" && val !== null)
			newObj[key] = removeDates(val);
		else newObj[key] = val;
	}
	return newObj;
}

/**
 * @description Must be used with a type assertion
 */
// eslint-disable-next-line @typescript-eslint/ban-types, @typescript-eslint/no-explicit-any
export function reviveDates<T extends object>(obj: T): any {
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	const newObj: any = Array.isArray(obj) ? [] : {};
	for (const [key, val] of Object.entries(obj)) {
		if (typeof val === "string" && dateRegex.test(val))
			newObj[key] = new Date(val);
		else if (typeof val === "object" && val !== null)
			newObj[key] = reviveDates(val);
		else newObj[key] = val;
	}
	return newObj;
}

// eslint-disable-next-line @typescript-eslint/ban-types
export type NoDates<T extends object> = {
	[K in keyof T]: T[K] extends Date
		? string
		: // eslint-disable-next-line @typescript-eslint/ban-types
		T[K] extends object
		? NoDates<T[K]>
		: T[K];
};

const obj = {
	grades: [
		{
			name: "Frise historique",
			value: 15,
			classMax: 17,
			classAvg: 13.28,
			classMin: 9,
			outOf: 20,
			weight: 1,
			unweighted: false,
			isLetter: false,
			date: "2021-09-07T00:00:00.000Z",
			dateTyped: "2021-09-24T00:00:00.000Z",
			periodCode: "A001",
			subjectCode: "NSINF",
			subjectName: "NUMERIQUE SC.INFORM.",
			elements: [],
		},
		{
			name: "Activité sur les cristaux",
			value: 20,
			classMax: 20,
			classAvg: 15.45,
			classMin: 7,
			outOf: 20,
			weight: 1,
			unweighted: false,
			isLetter: false,
			date: "2021-09-16T00:00:00.000Z",
			dateTyped: "2021-09-29T00:00:00.000Z",
			periodCode: "A001",
			subjectCode: "G-SCI",
			subjectName: "ENSEIGN.SCIENTIFIQUE",
			elements: [],
		},
		{
			name: "Interrogation",
			value: 10,
			classMax: 10,
			classAvg: 9.02,
			classMin: 6.9,
			outOf: 10,
			weight: 1,
			unweighted: false,
			isLetter: false,
			date: "2021-09-16T00:00:00.000Z",
			dateTyped: "2021-09-16T00:00:00.000Z",
			periodCode: "A001",
			subjectCode: "HI-GE",
			subjectName: "HISTOIRE-GEOGRAPHIE",
			elements: [],
		},
		{
			name: "Interrogation ch1",
			value: 15.25,
			classMax: 20,
			classAvg: 15,
			classMin: 6,
			outOf: 20,
			weight: 2,
			unweighted: false,
			isLetter: false,
			date: "2021-09-19T00:00:00.000Z",
			dateTyped: "2021-09-28T00:00:00.000Z",
			periodCode: "A001",
			subjectCode: "MATHS",
			subjectName: "MATHEMATIQUES",
			elements: [],
		},
		{
			name: "EE",
			value: 14,
			classMax: 20,
			classAvg: 12.4,
			classMin: 6,
			outOf: 20,
			weight: 1,
			unweighted: false,
			isLetter: false,
			date: "2021-09-21T00:00:00.000Z",
			dateTyped: "2021-09-21T00:00:00.000Z",
			periodCode: "A001",
			subjectCode: "FRANC",
			subjectName: "FRANCAIS",
			elements: [],
		},
		{
			name: "EOC",
			value: 18,
			classMax: 19,
			classAvg: 15.6,
			classMin: 12,
			outOf: 20,
			weight: 1,
			unweighted: false,
			isLetter: false,
			date: "2021-09-22T00:00:00.000Z",
			dateTyped: "2021-09-15T00:00:00.000Z",
			periodCode: "A001",
			subjectCode: "AGL",
			subjectName: "ANGLAIS",
			elements: [],
		},
		{
			name: "QCM Html_CSS",
			value: 18.7,
			classMax: 18.7,
			classAvg: 14.46,
			classMin: 9.3,
			outOf: 20,
			weight: 1,
			unweighted: false,
			isLetter: false,
			date: "2021-09-24T00:00:00.000Z",
			dateTyped: "2021-09-24T00:00:00.000Z",
			periodCode: "A001",
			subjectCode: "NSINF",
			subjectName: "NUMERIQUE SC.INFORM.",
			elements: [],
		},
		{
			name: "Contrôle",
			value: 15,
			classMax: 17,
			classAvg: 12.26,
			classMin: 7,
			outOf: 20,
			weight: 3,
			unweighted: false,
			isLetter: false,
			date: "2021-09-28T00:00:00.000Z",
			dateTyped: "2021-09-28T00:00:00.000Z",
			periodCode: "A001",
			subjectCode: "FRANC",
			subjectName: "FRANCAIS",
			elements: [],
		},
		{
			name: "Analyse de Doc Histoire",
			value: 11,
			classMax: 15,
			classAvg: 11.95,
			classMin: 9,
			outOf: 20,
			weight: 2,
			unweighted: false,
			isLetter: false,
			date: "2021-09-29T00:00:00.000Z",
			dateTyped: "2021-10-14T00:00:00.000Z",
			periodCode: "A001",
			subjectCode: "HI-GE",
			subjectName: "HISTOIRE-GEOGRAPHIE",
			elements: [],
		},
		{
			name: "Eval 1",
			value: 20,
			classMax: 20,
			classAvg: 19,
			classMin: 13,
			outOf: 20,
			weight: 1,
			unweighted: false,
			isLetter: false,
			date: "2021-09-30T00:00:00.000Z",
			dateTyped: "2021-09-30T00:00:00.000Z",
			periodCode: "A001",
			subjectCode: "PH-CH",
			subjectName: "PHYSIQUE-CHIMIE",
			elements: [],
		},
		{
			name: "TP Sept",
			value: 20,
			classMax: 20,
			classAvg: 17.54,
			classMin: 14,
			outOf: 20,
			weight: 1,
			unweighted: false,
			isLetter: false,
			date: "2021-09-30T00:00:00.000Z",
			dateTyped: "2021-09-30T00:00:00.000Z",
			periodCode: "A001",
			subjectCode: "PH-CH",
			subjectName: "PHYSIQUE-CHIMIE",
			elements: [],
		},
		{
			name: "Devoir maison 1",
			value: 20,
			classMax: 20,
			classAvg: 17.7,
			classMin: 14,
			outOf: 20,
			weight: 0.5,
			unweighted: false,
			isLetter: false,
			date: "2021-10-03T00:00:00.000Z",
			dateTyped: "2021-10-03T00:00:00.000Z",
			periodCode: "A001",
			subjectCode: "MATHS",
			subjectName: "MATHEMATIQUES",
			elements: [],
		},
		{
			name: "Contrôle 1",
			value: 18.5,
			classMax: 20,
			classAvg: 13.48,
			classMin: 7,
			outOf: 20,
			weight: 3,
			unweighted: false,
			isLetter: false,
			date: "2021-10-05T00:00:00.000Z",
			dateTyped: "2021-10-17T00:00:00.000Z",
			periodCode: "A001",
			subjectCode: "MATHS",
			subjectName: "MATHEMATIQUES",
			elements: [],
		},
		{
			name: "Oral en continu sur les vacances",
			value: 15,
			classMax: 20,
			classAvg: 14.26,
			classMin: 11,
			outOf: 20,
			weight: 2,
			unweighted: false,
			isLetter: false,
			date: "2021-10-05T00:00:00.000Z",
			dateTyped: "2021-10-05T00:00:00.000Z",
			periodCode: "A001",
			subjectCode: "ALL2",
			subjectName: "ALLEMAND",
			elements: [],
		},
		{
			name: "DM ",
			value: 20,
			classMax: 20,
			classAvg: 13.15,
			classMin: 4,
			outOf: 20,
			weight: 1,
			unweighted: false,
			isLetter: false,
			date: "2021-10-06T00:00:00.000Z",
			dateTyped: "2021-10-06T00:00:00.000Z",
			periodCode: "A001",
			subjectCode: "FRANC",
			subjectName: "FRANCAIS",
			elements: [],
		},
		{
			name: "Mini-projet html_css",
			value: 19,
			classMax: 19,
			classAvg: 14.88,
			classMin: 9,
			outOf: 20,
			weight: 1,
			unweighted: false,
			isLetter: false,
			date: "2021-10-07T00:00:00.000Z",
			dateTyped: "2021-09-24T00:00:00.000Z",
			periodCode: "A001",
			subjectCode: "NSINF",
			subjectName: "NUMERIQUE SC.INFORM.",
			elements: [],
		},
		{
			name: "CO",
			value: 15,
			classMax: 17,
			classAvg: 13.57,
			classMin: 6,
			outOf: 20,
			weight: 1,
			unweighted: false,
			isLetter: false,
			date: "2021-10-11T00:00:00.000Z",
			dateTyped: "2021-10-03T00:00:00.000Z",
			periodCode: "A001",
			subjectCode: "AGL",
			subjectName: "ANGLAIS",
			elements: [],
		},
		{
			name: "PPO en binôme",
			value: 9,
			classMax: 9,
			classAvg: 7.68,
			classMin: 5.5,
			outOf: 10,
			weight: 1,
			unweighted: false,
			isLetter: false,
			date: "2021-10-13T00:00:00.000Z",
			dateTyped: "2021-10-27T00:00:00.000Z",
			periodCode: "A001",
			subjectCode: "HI-GE",
			subjectName: "HISTOIRE-GEOGRAPHIE",
			elements: [],
		},
		{
			name: "Evaluation",
			value: 18,
			classMax: 20,
			classAvg: 15.33,
			classMin: 8,
			outOf: 20,
			weight: 1,
			unweighted: false,
			isLetter: false,
			date: "2021-10-14T00:00:00.000Z",
			dateTyped: "2021-10-14T00:00:00.000Z",
			periodCode: "A001",
			subjectCode: "G-SCI",
			subjectName: "ENSEIGN.SCIENTIFIQUE",
			elements: [],
			qcm: {
				id: 167,
				name: "QCM 1ES - Matière (cristaux et cellules)",
				startsAt: "2021-10-14T08:27:50.000Z",
			},
		},
		{
			name: "CC 1",
			value: 10.5,
			classMax: 20,
			classAvg: 10.54,
			classMin: 2,
			outOf: 20,
			weight: 3,
			unweighted: false,
			isLetter: false,
			date: "2021-10-18T00:00:00.000Z",
			dateTyped: "2021-10-18T00:00:00.000Z",
			periodCode: "A001",
			subjectCode: "PH-CH",
			subjectName: "PHYSIQUE-CHIMIE",
			elements: [],
		},
		{
			name: "DM ",
			value: 18,
			classMax: 19,
			classAvg: 14.13,
			classMin: 8,
			outOf: 20,
			weight: 1,
			unweighted: false,
			isLetter: false,
			date: "2021-10-18T00:00:00.000Z",
			dateTyped: "2021-10-18T00:00:00.000Z",
			periodCode: "A001",
			subjectCode: "FRANC",
			subjectName: "FRANCAIS",
			elements: [],
		},
		{
			name: "EE",
			value: 15,
			classMax: 17,
			classAvg: 12.93,
			classMin: 9,
			outOf: 20,
			weight: 2,
			unweighted: false,
			isLetter: false,
			date: "2021-10-20T00:00:00.000Z",
			dateTyped: "2021-10-08T00:00:00.000Z",
			periodCode: "A001",
			subjectCode: "AGL",
			subjectName: "ANGLAIS",
			elements: [],
		},
		{
			name: "TP Fer III",
			value: 20,
			classMax: 20,
			classAvg: 18.89,
			classMin: 17,
			outOf: 20,
			weight: 1,
			unweighted: false,
			isLetter: false,
			date: "2021-10-22T00:00:00.000Z",
			dateTyped: "2021-10-21T00:00:00.000Z",
			periodCode: "A001",
			subjectCode: "PH-CH",
			subjectName: "PHYSIQUE-CHIMIE",
			elements: [],
		},
	],
	periods: [
		{
			code: "A001",
			name: "1er Trimestre",
			yearly: false,
			closed: false,
			start: "2021-09-01T00:00:00.000Z",
			end: "2021-11-20T00:00:00.000Z",
			mockExam: false,
			headTeacher: "M. LOUIS LUCAS A.",
			council: {
				start: "2021-12-03T16:00:00.000Z",
				room: "CDI",
			},
			subjects: [
				{
					id: 4634,
					code: "FRANC",
					name: "FRANCAIS",
					weight: 5,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 134,
							name: "Mme GAUTHERIN E.",
						},
					],
					stats: {
						weightedAvg: 16.166666666666668,
						classAvg: 12.743333333333332,
					},
				},
				{
					id: 4636,
					code: "AGL",
					name: "ANGLAIS",
					weight: 2,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 283,
							name: "Mme ONYSZCZUK F.",
						},
					],
					stats: {
						weightedAvg: 15.75,
						classAvg: 13.7575,
					},
				},
				{
					id: 4640,
					code: "ALL2",
					name: "ALLEMAND",
					weight: 2,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 108,
							name: "Mme ENZWEILER J.",
						},
					],
					stats: {
						weightedAvg: 15,
						classAvg: 14.26,
					},
				},
				{
					id: 4631,
					code: "HI-GE",
					name: "HISTOIRE-GEOGRAPHIE",
					weight: 2,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 94,
							name: "M. DESTAING M.",
						},
					],
					stats: {
						weightedAvg: 15,
						classAvg: 14.325,
					},
				},
				{
					id: 4629,
					code: "EMC",
					name: "ENS. MORAL & CIVIQUE",
					weight: 0.5,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 94,
							name: "M. DESTAING M.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4623,
					code: "G-SCI",
					name: "ENSEIGN.SCIENTIFIQUE",
					weight: 1,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 226,
							name: "M. LOUIS LUCAS A.",
						},
					],
					stats: {
						weightedAvg: 19,
						classAvg: 15.389999999999999,
					},
				},
				{
					id: 4639,
					code: "MATHS",
					name: "MATHEMATIQUES",
					weight: 5,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 267,
							name: "M. MORENO S.",
						},
					],
					stats: {
						weightedAvg: 17.454545454545453,
						classAvg: 14.416363636363634,
					},
				},
				{
					id: 4627,
					code: "NSINF",
					name: "NUMERIQUE SC.INFORM.",
					weight: 5,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 631,
							name: "M. GRIESS S.",
						},
					],
					stats: {
						weightedAvg: 17.566666666666666,
						classAvg: 14.206666666666665,
					},
				},
				{
					id: 4626,
					code: "PH-CH",
					name: "PHYSIQUE-CHIMIE",
					weight: 5,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 421,
							name: "Mme RESLINGER-NAIT AMMOU F.",
						},
					],
					stats: {
						weightedAvg: 15.25,
						classAvg: 14.508333333333333,
					},
				},
				{
					id: 4622,
					code: "EPS",
					name: "ED.PHYSIQUE & SPORT.",
					weight: 1,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 367,
							name: "M. TRITZ G.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4625,
					code: "CATHO",
					name: "ENS.RELIG.CATHOLIQUE",
					weight: 0,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 249,
							name: "M. MELLE J.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
			],
			stats: {
				weightedAvg: 16.39590347923681,
				classAvg: 14.053647586980917,
			},
		},
		{
			code: "A002",
			name: "2ème Trimestre",
			yearly: false,
			closed: false,
			start: "2021-11-22T00:00:00.000Z",
			end: "2022-03-05T00:00:00.000Z",
			mockExam: false,
			headTeacher: "M. LOUIS LUCAS A.",
			council: {
				start: "2022-03-11T16:00:00.000Z",
			},
			subjects: [
				{
					id: 4634,
					code: "FRANC",
					name: "FRANCAIS",
					weight: 5,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 134,
							name: "Mme GAUTHERIN E.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4636,
					code: "AGL",
					name: "ANGLAIS",
					weight: 2,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 283,
							name: "Mme ONYSZCZUK F.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4640,
					code: "ALL2",
					name: "ALLEMAND",
					weight: 2,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 108,
							name: "Mme ENZWEILER J.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4631,
					code: "HI-GE",
					name: "HISTOIRE-GEOGRAPHIE",
					weight: 2,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 94,
							name: "M. DESTAING M.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4629,
					code: "EMC",
					name: "ENS. MORAL & CIVIQUE",
					weight: 0.5,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 94,
							name: "M. DESTAING M.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4623,
					code: "G-SCI",
					name: "ENSEIGN.SCIENTIFIQUE",
					weight: 1,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 226,
							name: "M. LOUIS LUCAS A.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4639,
					code: "MATHS",
					name: "MATHEMATIQUES",
					weight: 5,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 267,
							name: "M. MORENO S.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4627,
					code: "NSINF",
					name: "NUMERIQUE SC.INFORM.",
					weight: 5,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 631,
							name: "M. GRIESS S.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4626,
					code: "PH-CH",
					name: "PHYSIQUE-CHIMIE",
					weight: 5,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 421,
							name: "Mme RESLINGER-NAIT AMMOU F.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4622,
					code: "EPS",
					name: "ED.PHYSIQUE & SPORT.",
					weight: 1,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 367,
							name: "M. TRITZ G.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4625,
					code: "CATHO",
					name: "ENS.RELIG.CATHOLIQUE",
					weight: 0,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 249,
							name: "M. MELLE J.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
			],
			stats: {
				weightedAvg: null,
				classAvg: null,
			},
		},
		{
			code: "A002X001",
			name: "DNB Blanc n°1",
			yearly: false,
			closed: false,
			start: "2021-11-22T00:00:00.000Z",
			end: "2022-03-05T00:00:00.000Z",
			mockExam: true,
			headTeacher: "M. LOUIS LUCAS A.",
			subjects: [
				{
					id: 4636,
					code: "AGL",
					name: "ANGLAIS",
					weight: 2,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 283,
							name: "Mme ONYSZCZUK F.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4640,
					code: "ALL2",
					name: "ALLEMAND LV2",
					weight: 1,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 108,
							name: "Mme ENZWEILER J.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4629,
					code: "EMC",
					name: "ENS. MORAL & CIVIQUE",
					weight: 1,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 94,
							name: "M. DESTAING M.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4634,
					code: "FRANC",
					name: "FRANCAIS",
					weight: 1,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 134,
							name: "Mme GAUTHERIN E.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4623,
					code: "G-SCI",
					name: "ENSEIGN.SCIENTIFIQUE",
					weight: 1,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 226,
							name: "M. LOUIS LUCAS A.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4631,
					code: "HI-GE",
					name: "HISTOIRE-GEOGRAPHIE",
					weight: 1,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 94,
							name: "M. DESTAING M.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4639,
					code: "MATHS",
					name: "MATHEMATIQUES",
					weight: 1,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 267,
							name: "M. MORENO S.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4627,
					code: "NSINF",
					name: "NUMERIQUE SC.INFORM.",
					weight: 5,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 631,
							name: "M. GRIESS S.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4626,
					code: "PH-CH",
					name: "PHYSIQUE-CHIMIE",
					weight: 1,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 421,
							name: "Mme RESLINGER-NAIT AMMOU F.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
			],
			stats: {
				weightedAvg: null,
				classAvg: null,
			},
		},
		{
			code: "A003",
			name: "3ème Trimestre",
			yearly: false,
			closed: false,
			start: "2022-03-07T00:00:00.000Z",
			end: "2022-07-07T00:00:00.000Z",
			mockExam: false,
			headTeacher: "M. LOUIS LUCAS A.",
			council: {
				start: "2022-07-03T16:00:00.000Z",
			},
			subjects: [
				{
					id: 4634,
					code: "FRANC",
					name: "FRANCAIS",
					weight: 5,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 134,
							name: "Mme GAUTHERIN E.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4636,
					code: "AGL",
					name: "ANGLAIS",
					weight: 2,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 283,
							name: "Mme ONYSZCZUK F.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4640,
					code: "ALL2",
					name: "ALLEMAND",
					weight: 2,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 108,
							name: "Mme ENZWEILER J.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4631,
					code: "HI-GE",
					name: "HISTOIRE-GEOGRAPHIE",
					weight: 2,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 94,
							name: "M. DESTAING M.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4629,
					code: "EMC",
					name: "ENS. MORAL & CIVIQUE",
					weight: 0.5,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 94,
							name: "M. DESTAING M.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4623,
					code: "G-SCI",
					name: "ENSEIGN.SCIENTIFIQUE",
					weight: 1,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 226,
							name: "M. LOUIS LUCAS A.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4639,
					code: "MATHS",
					name: "MATHEMATIQUES",
					weight: 5,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 267,
							name: "M. MORENO S.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4627,
					code: "NSINF",
					name: "NUMERIQUE SC.INFORM.",
					weight: 5,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 631,
							name: "M. GRIESS S.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4626,
					code: "PH-CH",
					name: "PHYSIQUE-CHIMIE",
					weight: 5,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 421,
							name: "Mme RESLINGER-NAIT AMMOU F.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4622,
					code: "EPS",
					name: "ED.PHYSIQUE & SPORT.",
					weight: 1,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 367,
							name: "M. TRITZ G.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4625,
					code: "CATHO",
					name: "ENS.RELIG.CATHOLIQUE",
					weight: 0,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 249,
							name: "M. MELLE J.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
			],
			stats: {
				weightedAvg: null,
				classAvg: null,
			},
		},
		{
			code: "A003X001",
			name: "DNB Blanc n°2",
			yearly: false,
			closed: false,
			start: "2022-03-07T00:00:00.000Z",
			end: "2022-07-07T00:00:00.000Z",
			mockExam: true,
			headTeacher: "M. LOUIS LUCAS A.",
			subjects: [
				{
					id: 4636,
					code: "AGL",
					name: "ANGLAIS",
					weight: 2,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 283,
							name: "Mme ONYSZCZUK F.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4640,
					code: "ALL2",
					name: "ALLEMAND LV2",
					weight: 1,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 108,
							name: "Mme ENZWEILER J.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4629,
					code: "EMC",
					name: "ENS. MORAL & CIVIQUE",
					weight: 1,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 94,
							name: "M. DESTAING M.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4634,
					code: "FRANC",
					name: "FRANCAIS",
					weight: 1,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 134,
							name: "Mme GAUTHERIN E.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4623,
					code: "G-SCI",
					name: "ENSEIGN.SCIENTIFIQUE",
					weight: 1,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 226,
							name: "M. LOUIS LUCAS A.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4631,
					code: "HI-GE",
					name: "HISTOIRE-GEOGRAPHIE",
					weight: 1,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 94,
							name: "M. DESTAING M.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4639,
					code: "MATHS",
					name: "MATHEMATIQUES",
					weight: 1,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 267,
							name: "M. MORENO S.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4627,
					code: "NSINF",
					name: "NUMERIQUE SC.INFORM.",
					weight: 5,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 631,
							name: "M. GRIESS S.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4626,
					code: "PH-CH",
					name: "PHYSIQUE-CHIMIE",
					weight: 1,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 421,
							name: "Mme RESLINGER-NAIT AMMOU F.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
			],
			stats: {
				weightedAvg: null,
				classAvg: null,
			},
		},
		{
			code: "A999Z",
			name: "Année",
			yearly: true,
			closed: false,
			start: "2021-09-01T00:00:00.000Z",
			end: "2022-07-07T00:00:00.000Z",
			mockExam: false,
			headTeacher: "M. LOUIS LUCAS A.",
			subjects: [
				{
					id: 4634,
					code: "FRANC",
					name: "FRANCAIS",
					weight: 5,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 134,
							name: "Mme GAUTHERIN E.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4636,
					code: "AGL",
					name: "ANGLAIS",
					weight: 2,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 283,
							name: "Mme ONYSZCZUK F.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4640,
					code: "ALL2",
					name: "ALLEMAND",
					weight: 2,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 108,
							name: "Mme ENZWEILER J.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4631,
					code: "HI-GE",
					name: "HISTOIRE-GEOGRAPHIE",
					weight: 2,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 94,
							name: "M. DESTAING M.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4629,
					code: "EMC",
					name: "ENS. MORAL & CIVIQUE",
					weight: 0.5,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 94,
							name: "M. DESTAING M.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4623,
					code: "G-SCI",
					name: "ENSEIGN.SCIENTIFIQUE",
					weight: 1,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 226,
							name: "M. LOUIS LUCAS A.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4639,
					code: "MATHS",
					name: "MATHEMATIQUES",
					weight: 5,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 267,
							name: "M. MORENO S.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4627,
					code: "NSINF",
					name: "NUMERIQUE SC.INFORM.",
					weight: 5,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 631,
							name: "M. GRIESS S.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4626,
					code: "PH-CH",
					name: "PHYSIQUE-CHIMIE",
					weight: 5,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 421,
							name: "Mme RESLINGER-NAIT AMMOU F.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4622,
					code: "EPS",
					name: "ED.PHYSIQUE & SPORT.",
					weight: 1,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 367,
							name: "M. TRITZ G.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
				{
					id: 4625,
					code: "CATHO",
					name: "ENS.RELIG.CATHOLIQUE",
					weight: 0,
					headcount: 0,
					rank: 0,
					minorSubject: false,
					group: false,
					groupId: 0,
					appraisals: [],
					option: 0,
					teachers: [
						{
							id: 249,
							name: "M. MELLE J.",
						},
					],
					stats: {
						weightedAvg: null,
						classAvg: null,
					},
				},
			],
			stats: {
				weightedAvg: null,
				classAvg: null,
			},
		},
	],
	_id: "617bfb2d7fb3c71361db13f6",
	user: "6145cc4e7866c244c5949da6",
	schoolYear: "2021-2022",
	res: {
		periodes: [
			{
				idPeriode: "A001",
				codePeriode: "A001",
				periode: "1er Trimestre",
				annuel: false,
				dateDebut: "2021-09-01",
				dateFin: "2021-11-20",
				examenBlanc: false,
				cloture: false,
				dateConseil: "2021-12-03",
				heureConseil: "17:00",
				salleConseil: "CDI",
				moyNbreJoursApresConseil: -1,
				ensembleMatieres: {
					dateCalcul: "",
					nomPP: "M. LOUIS LUCAS A.",
					nomCE: "",
					decisionDuConseil: "",
					disciplines: [
						{
							id: 4634,
							codeMatiere: "FRANC",
							codeSousMatiere: "",
							discipline: "FRANCAIS",
							coef: 5,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 134,
									nom: "Mme GAUTHERIN E.",
								},
							],
						},
						{
							id: 4636,
							codeMatiere: "AGL",
							codeSousMatiere: "",
							discipline: "ANGLAIS",
							coef: 2,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 283,
									nom: "Mme ONYSZCZUK F.",
								},
							],
						},
						{
							id: 4640,
							codeMatiere: "ALL2",
							codeSousMatiere: "",
							discipline: "ALLEMAND",
							coef: 2,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 108,
									nom: "Mme ENZWEILER J.",
								},
							],
						},
						{
							id: 4631,
							codeMatiere: "HI-GE",
							codeSousMatiere: "",
							discipline: "HISTOIRE-GEOGRAPHIE",
							coef: 2,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 94,
									nom: "M. DESTAING M.",
								},
							],
						},
						{
							id: 4629,
							codeMatiere: "EMC",
							codeSousMatiere: "",
							discipline: "ENS. MORAL & CIVIQUE",
							coef: 0.5,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 94,
									nom: "M. DESTAING M.",
								},
							],
						},
						{
							id: 4623,
							codeMatiere: "G-SCI",
							codeSousMatiere: "",
							discipline: "ENSEIGN.SCIENTIFIQUE",
							coef: 1,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 226,
									nom: "M. LOUIS LUCAS A.",
								},
							],
						},
						{
							id: 4639,
							codeMatiere: "MATHS",
							codeSousMatiere: "",
							discipline: "MATHEMATIQUES",
							coef: 5,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 267,
									nom: "M. MORENO S.",
								},
							],
						},
						{
							id: 4627,
							codeMatiere: "NSINF",
							codeSousMatiere: "",
							discipline: "NUMERIQUE SC.INFORM.",
							coef: 5,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 631,
									nom: "M. GRIESS S.",
								},
							],
						},
						{
							id: 4626,
							codeMatiere: "PH-CH",
							codeSousMatiere: "",
							discipline: "PHYSIQUE-CHIMIE",
							coef: 5,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 421,
									nom: "Mme RESLINGER-NAIT AMMOU F.",
								},
							],
						},
						{
							id: 4622,
							codeMatiere: "EPS",
							codeSousMatiere: "",
							discipline: "ED.PHYSIQUE & SPORT.",
							coef: 1,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 367,
									nom: "M. TRITZ G.",
								},
							],
						},
						{
							id: 4625,
							codeMatiere: "CATHO",
							codeSousMatiere: "",
							discipline: "ENS.RELIG.CATHOLIQUE",
							coef: 0,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 249,
									nom: "M. MELLE J.",
								},
							],
						},
					],
					disciplinesSimulation: [],
				},
			},
			{
				idPeriode: "A002",
				codePeriode: "A002",
				periode: "2ème Trimestre",
				annuel: false,
				dateDebut: "2021-11-22",
				dateFin: "2022-03-05",
				examenBlanc: false,
				cloture: false,
				dateConseil: "2022-03-11",
				heureConseil: "17:00",
				moyNbreJoursApresConseil: -1,
				ensembleMatieres: {
					dateCalcul: "",
					nomPP: "M. LOUIS LUCAS A.",
					nomCE: "",
					decisionDuConseil: "",
					disciplines: [
						{
							id: 4634,
							codeMatiere: "FRANC",
							codeSousMatiere: "",
							discipline: "FRANCAIS",
							coef: 5,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 134,
									nom: "Mme GAUTHERIN E.",
								},
							],
						},
						{
							id: 4636,
							codeMatiere: "AGL",
							codeSousMatiere: "",
							discipline: "ANGLAIS",
							coef: 2,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 283,
									nom: "Mme ONYSZCZUK F.",
								},
							],
						},
						{
							id: 4640,
							codeMatiere: "ALL2",
							codeSousMatiere: "",
							discipline: "ALLEMAND",
							coef: 2,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 108,
									nom: "Mme ENZWEILER J.",
								},
							],
						},
						{
							id: 4631,
							codeMatiere: "HI-GE",
							codeSousMatiere: "",
							discipline: "HISTOIRE-GEOGRAPHIE",
							coef: 2,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 94,
									nom: "M. DESTAING M.",
								},
							],
						},
						{
							id: 4629,
							codeMatiere: "EMC",
							codeSousMatiere: "",
							discipline: "ENS. MORAL & CIVIQUE",
							coef: 0.5,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 94,
									nom: "M. DESTAING M.",
								},
							],
						},
						{
							id: 4623,
							codeMatiere: "G-SCI",
							codeSousMatiere: "",
							discipline: "ENSEIGN.SCIENTIFIQUE",
							coef: 1,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 226,
									nom: "M. LOUIS LUCAS A.",
								},
							],
						},
						{
							id: 4639,
							codeMatiere: "MATHS",
							codeSousMatiere: "",
							discipline: "MATHEMATIQUES",
							coef: 5,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 267,
									nom: "M. MORENO S.",
								},
							],
						},
						{
							id: 4627,
							codeMatiere: "NSINF",
							codeSousMatiere: "",
							discipline: "NUMERIQUE SC.INFORM.",
							coef: 5,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 631,
									nom: "M. GRIESS S.",
								},
							],
						},
						{
							id: 4626,
							codeMatiere: "PH-CH",
							codeSousMatiere: "",
							discipline: "PHYSIQUE-CHIMIE",
							coef: 5,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 421,
									nom: "Mme RESLINGER-NAIT AMMOU F.",
								},
							],
						},
						{
							id: 4622,
							codeMatiere: "EPS",
							codeSousMatiere: "",
							discipline: "ED.PHYSIQUE & SPORT.",
							coef: 1,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 367,
									nom: "M. TRITZ G.",
								},
							],
						},
						{
							id: 4625,
							codeMatiere: "CATHO",
							codeSousMatiere: "",
							discipline: "ENS.RELIG.CATHOLIQUE",
							coef: 0,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 249,
									nom: "M. MELLE J.",
								},
							],
						},
					],
					disciplinesSimulation: [],
				},
			},
			{
				idPeriode: "A002X001",
				codePeriode: "A002X001",
				periode: "DNB Blanc n°1",
				annuel: false,
				dateDebut: "2021-11-22",
				dateFin: "2022-03-05",
				examenBlanc: true,
				cloture: false,
				moyNbreJoursApresConseil: -1,
				ensembleMatieres: {
					dateCalcul: "",
					nomPP: "M. LOUIS LUCAS A.",
					nomCE: "",
					decisionDuConseil: "",
					disciplines: [
						{
							id: 4636,
							codeMatiere: "AGL",
							codeSousMatiere: "",
							discipline: "ANGLAIS",
							coef: 2,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 283,
									nom: "Mme ONYSZCZUK F.",
								},
							],
						},
						{
							id: 4640,
							codeMatiere: "ALL2",
							codeSousMatiere: "",
							discipline: "ALLEMAND LV2",
							coef: 1,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 108,
									nom: "Mme ENZWEILER J.",
								},
							],
						},
						{
							id: 4629,
							codeMatiere: "EMC",
							codeSousMatiere: "",
							discipline: "ENS. MORAL & CIVIQUE",
							coef: 1,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 94,
									nom: "M. DESTAING M.",
								},
							],
						},
						{
							id: 4634,
							codeMatiere: "FRANC",
							codeSousMatiere: "",
							discipline: "FRANCAIS",
							coef: 1,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 134,
									nom: "Mme GAUTHERIN E.",
								},
							],
						},
						{
							id: 4623,
							codeMatiere: "G-SCI",
							codeSousMatiere: "",
							discipline: "ENSEIGN.SCIENTIFIQUE",
							coef: 1,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 226,
									nom: "M. LOUIS LUCAS A.",
								},
							],
						},
						{
							id: 4631,
							codeMatiere: "HI-GE",
							codeSousMatiere: "",
							discipline: "HISTOIRE-GEOGRAPHIE",
							coef: 1,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 94,
									nom: "M. DESTAING M.",
								},
							],
						},
						{
							id: 4639,
							codeMatiere: "MATHS",
							codeSousMatiere: "",
							discipline: "MATHEMATIQUES",
							coef: 1,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 267,
									nom: "M. MORENO S.",
								},
							],
						},
						{
							id: 4627,
							codeMatiere: "NSINF",
							codeSousMatiere: "",
							discipline: "NUMERIQUE SC.INFORM.",
							coef: 5,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 631,
									nom: "M. GRIESS S.",
								},
							],
						},
						{
							id: 4626,
							codeMatiere: "PH-CH",
							codeSousMatiere: "",
							discipline: "PHYSIQUE-CHIMIE",
							coef: 1,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 421,
									nom: "Mme RESLINGER-NAIT AMMOU F.",
								},
							],
						},
					],
					disciplinesSimulation: [],
				},
			},
			{
				idPeriode: "A003",
				codePeriode: "A003",
				periode: "3ème Trimestre",
				annuel: false,
				dateDebut: "2022-03-07",
				dateFin: "2022-07-07",
				examenBlanc: false,
				cloture: false,
				dateConseil: "2022-07-03",
				heureConseil: "18:00",
				moyNbreJoursApresConseil: -1,
				ensembleMatieres: {
					dateCalcul: "",
					nomPP: "M. LOUIS LUCAS A.",
					nomCE: "",
					decisionDuConseil: "",
					disciplines: [
						{
							id: 4634,
							codeMatiere: "FRANC",
							codeSousMatiere: "",
							discipline: "FRANCAIS",
							coef: 5,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 134,
									nom: "Mme GAUTHERIN E.",
								},
							],
						},
						{
							id: 4636,
							codeMatiere: "AGL",
							codeSousMatiere: "",
							discipline: "ANGLAIS",
							coef: 2,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 283,
									nom: "Mme ONYSZCZUK F.",
								},
							],
						},
						{
							id: 4640,
							codeMatiere: "ALL2",
							codeSousMatiere: "",
							discipline: "ALLEMAND",
							coef: 2,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 108,
									nom: "Mme ENZWEILER J.",
								},
							],
						},
						{
							id: 4631,
							codeMatiere: "HI-GE",
							codeSousMatiere: "",
							discipline: "HISTOIRE-GEOGRAPHIE",
							coef: 2,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 94,
									nom: "M. DESTAING M.",
								},
							],
						},
						{
							id: 4629,
							codeMatiere: "EMC",
							codeSousMatiere: "",
							discipline: "ENS. MORAL & CIVIQUE",
							coef: 0.5,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 94,
									nom: "M. DESTAING M.",
								},
							],
						},
						{
							id: 4623,
							codeMatiere: "G-SCI",
							codeSousMatiere: "",
							discipline: "ENSEIGN.SCIENTIFIQUE",
							coef: 1,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 226,
									nom: "M. LOUIS LUCAS A.",
								},
							],
						},
						{
							id: 4639,
							codeMatiere: "MATHS",
							codeSousMatiere: "",
							discipline: "MATHEMATIQUES",
							coef: 5,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 267,
									nom: "M. MORENO S.",
								},
							],
						},
						{
							id: 4627,
							codeMatiere: "NSINF",
							codeSousMatiere: "",
							discipline: "NUMERIQUE SC.INFORM.",
							coef: 5,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 631,
									nom: "M. GRIESS S.",
								},
							],
						},
						{
							id: 4626,
							codeMatiere: "PH-CH",
							codeSousMatiere: "",
							discipline: "PHYSIQUE-CHIMIE",
							coef: 5,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 421,
									nom: "Mme RESLINGER-NAIT AMMOU F.",
								},
							],
						},
						{
							id: 4622,
							codeMatiere: "EPS",
							codeSousMatiere: "",
							discipline: "ED.PHYSIQUE & SPORT.",
							coef: 1,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 367,
									nom: "M. TRITZ G.",
								},
							],
						},
						{
							id: 4625,
							codeMatiere: "CATHO",
							codeSousMatiere: "",
							discipline: "ENS.RELIG.CATHOLIQUE",
							coef: 0,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 249,
									nom: "M. MELLE J.",
								},
							],
						},
					],
					disciplinesSimulation: [],
				},
			},
			{
				idPeriode: "A003X001",
				codePeriode: "A003X001",
				periode: "DNB Blanc n°2",
				annuel: false,
				dateDebut: "2022-03-07",
				dateFin: "2022-07-07",
				examenBlanc: true,
				cloture: false,
				moyNbreJoursApresConseil: -1,
				ensembleMatieres: {
					dateCalcul: "",
					nomPP: "M. LOUIS LUCAS A.",
					nomCE: "",
					decisionDuConseil: "",
					disciplines: [
						{
							id: 4636,
							codeMatiere: "AGL",
							codeSousMatiere: "",
							discipline: "ANGLAIS",
							coef: 2,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 283,
									nom: "Mme ONYSZCZUK F.",
								},
							],
						},
						{
							id: 4640,
							codeMatiere: "ALL2",
							codeSousMatiere: "",
							discipline: "ALLEMAND LV2",
							coef: 1,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 108,
									nom: "Mme ENZWEILER J.",
								},
							],
						},
						{
							id: 4629,
							codeMatiere: "EMC",
							codeSousMatiere: "",
							discipline: "ENS. MORAL & CIVIQUE",
							coef: 1,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 94,
									nom: "M. DESTAING M.",
								},
							],
						},
						{
							id: 4634,
							codeMatiere: "FRANC",
							codeSousMatiere: "",
							discipline: "FRANCAIS",
							coef: 1,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 134,
									nom: "Mme GAUTHERIN E.",
								},
							],
						},
						{
							id: 4623,
							codeMatiere: "G-SCI",
							codeSousMatiere: "",
							discipline: "ENSEIGN.SCIENTIFIQUE",
							coef: 1,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 226,
									nom: "M. LOUIS LUCAS A.",
								},
							],
						},
						{
							id: 4631,
							codeMatiere: "HI-GE",
							codeSousMatiere: "",
							discipline: "HISTOIRE-GEOGRAPHIE",
							coef: 1,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 94,
									nom: "M. DESTAING M.",
								},
							],
						},
						{
							id: 4639,
							codeMatiere: "MATHS",
							codeSousMatiere: "",
							discipline: "MATHEMATIQUES",
							coef: 1,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 267,
									nom: "M. MORENO S.",
								},
							],
						},
						{
							id: 4627,
							codeMatiere: "NSINF",
							codeSousMatiere: "",
							discipline: "NUMERIQUE SC.INFORM.",
							coef: 5,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 631,
									nom: "M. GRIESS S.",
								},
							],
						},
						{
							id: 4626,
							codeMatiere: "PH-CH",
							codeSousMatiere: "",
							discipline: "PHYSIQUE-CHIMIE",
							coef: 1,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 421,
									nom: "Mme RESLINGER-NAIT AMMOU F.",
								},
							],
						},
					],
					disciplinesSimulation: [],
				},
			},
			{
				idPeriode: "A999Z",
				codePeriode: "A999Z",
				periode: "Année",
				annuel: true,
				dateDebut: "2021-09-01",
				dateFin: "2022-07-07",
				examenBlanc: false,
				cloture: false,
				moyNbreJoursApresConseil: -1,
				ensembleMatieres: {
					dateCalcul: "",
					nomPP: "M. LOUIS LUCAS A.",
					nomCE: "",
					decisionDuConseil: "",
					disciplines: [
						{
							id: 4634,
							codeMatiere: "FRANC",
							codeSousMatiere: "",
							discipline: "FRANCAIS",
							coef: 5,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 134,
									nom: "Mme GAUTHERIN E.",
								},
							],
						},
						{
							id: 4636,
							codeMatiere: "AGL",
							codeSousMatiere: "",
							discipline: "ANGLAIS",
							coef: 2,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 283,
									nom: "Mme ONYSZCZUK F.",
								},
							],
						},
						{
							id: 4640,
							codeMatiere: "ALL2",
							codeSousMatiere: "",
							discipline: "ALLEMAND",
							coef: 2,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 108,
									nom: "Mme ENZWEILER J.",
								},
							],
						},
						{
							id: 4631,
							codeMatiere: "HI-GE",
							codeSousMatiere: "",
							discipline: "HISTOIRE-GEOGRAPHIE",
							coef: 2,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 94,
									nom: "M. DESTAING M.",
								},
							],
						},
						{
							id: 4629,
							codeMatiere: "EMC",
							codeSousMatiere: "",
							discipline: "ENS. MORAL & CIVIQUE",
							coef: 0.5,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 94,
									nom: "M. DESTAING M.",
								},
							],
						},
						{
							id: 4623,
							codeMatiere: "G-SCI",
							codeSousMatiere: "",
							discipline: "ENSEIGN.SCIENTIFIQUE",
							coef: 1,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 226,
									nom: "M. LOUIS LUCAS A.",
								},
							],
						},
						{
							id: 4639,
							codeMatiere: "MATHS",
							codeSousMatiere: "",
							discipline: "MATHEMATIQUES",
							coef: 5,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 267,
									nom: "M. MORENO S.",
								},
							],
						},
						{
							id: 4627,
							codeMatiere: "NSINF",
							codeSousMatiere: "",
							discipline: "NUMERIQUE SC.INFORM.",
							coef: 5,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 631,
									nom: "M. GRIESS S.",
								},
							],
						},
						{
							id: 4626,
							codeMatiere: "PH-CH",
							codeSousMatiere: "",
							discipline: "PHYSIQUE-CHIMIE",
							coef: 5,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 421,
									nom: "Mme RESLINGER-NAIT AMMOU F.",
								},
							],
						},
						{
							id: 4622,
							codeMatiere: "EPS",
							codeSousMatiere: "",
							discipline: "ED.PHYSIQUE & SPORT.",
							coef: 1,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 367,
									nom: "M. TRITZ G.",
								},
							],
						},
						{
							id: 4625,
							codeMatiere: "CATHO",
							codeSousMatiere: "",
							discipline: "ENS.RELIG.CATHOLIQUE",
							coef: 0,
							effectif: 0,
							rang: 0,
							groupeMatiere: false,
							idGroupeMatiere: 0,
							option: 0,
							sousMatiere: false,
							saisieAppreciationSSMat: false,
							professeurs: [
								{
									id: 249,
									nom: "M. MELLE J.",
								},
							],
						},
					],
					disciplinesSimulation: [],
				},
			},
		],
		notes: [
			{
				devoir: "Frise historique",
				codePeriode: "A001",
				codeMatiere: "NSINF",
				libelleMatiere: "NUMERIQUE SC.INFORM.",
				codeSousMatiere: "",
				typeDevoir: "Devoir sur table",
				enLettre: false,
				coef: "1",
				noteSur: "20",
				valeur: "15",
				nonSignificatif: false,
				date: "2021-09-07",
				dateSaisie: "2021-09-24",
				valeurisee: false,
				moyenneClasse: "13.28",
				minClasse: "9.00",
				maxClasse: "17.00",
				elementsProgramme: [],
			},
			{
				devoir: "Activité sur les cristaux",
				codePeriode: "A001",
				codeMatiere: "G-SCI",
				libelleMatiere: "ENSEIGN.SCIENTIFIQUE",
				codeSousMatiere: "",
				typeDevoir: "Devoir sur table",
				enLettre: false,
				coef: "1",
				noteSur: "20",
				valeur: "20",
				nonSignificatif: false,
				date: "2021-09-16",
				dateSaisie: "2021-09-29",
				valeurisee: false,
				moyenneClasse: "15.45",
				minClasse: "7.00",
				maxClasse: "20.00",
				elementsProgramme: [],
			},
			{
				devoir: "Interrogation",
				codePeriode: "A001",
				codeMatiere: "HI-GE",
				libelleMatiere: "HISTOIRE-GEOGRAPHIE",
				codeSousMatiere: "",
				typeDevoir: "",
				enLettre: false,
				coef: "1",
				noteSur: "10",
				valeur: "10",
				nonSignificatif: false,
				date: "2021-09-16",
				dateSaisie: "2021-09-16",
				valeurisee: false,
				moyenneClasse: "9.02",
				minClasse: "6.90",
				maxClasse: "10.00",
				elementsProgramme: [],
			},
			{
				devoir: "Interrogation ch1",
				codePeriode: "A001",
				codeMatiere: "MATHS",
				libelleMatiere: "MATHEMATIQUES",
				codeSousMatiere: "",
				typeDevoir: "",
				enLettre: false,
				coef: "2",
				noteSur: "20",
				valeur: "15,25",
				nonSignificatif: false,
				date: "2021-09-19",
				dateSaisie: "2021-09-28",
				valeurisee: false,
				moyenneClasse: "15.00",
				minClasse: "6.00",
				maxClasse: "20.00",
				elementsProgramme: [],
			},
			{
				devoir: "EE",
				codePeriode: "A001",
				codeMatiere: "FRANC",
				libelleMatiere: "FRANCAIS",
				codeSousMatiere: "",
				typeDevoir: "",
				enLettre: false,
				coef: "1",
				noteSur: "20",
				valeur: "14",
				nonSignificatif: false,
				date: "2021-09-21",
				dateSaisie: "2021-09-21",
				valeurisee: false,
				moyenneClasse: "12.40",
				minClasse: "6.00",
				maxClasse: "20.00",
				elementsProgramme: [],
			},
			{
				devoir: "EOC",
				codePeriode: "A001",
				codeMatiere: "AGL",
				libelleMatiere: "ANGLAIS",
				codeSousMatiere: "",
				typeDevoir: "",
				enLettre: false,
				coef: "1",
				noteSur: "20",
				valeur: "18",
				nonSignificatif: false,
				date: "2021-09-22",
				dateSaisie: "2021-09-15",
				valeurisee: false,
				moyenneClasse: "15.60",
				minClasse: "12.00",
				maxClasse: "19.00",
				elementsProgramme: [],
			},
			{
				devoir: "QCM Html_CSS",
				codePeriode: "A001",
				codeMatiere: "NSINF",
				libelleMatiere: "NUMERIQUE SC.INFORM.",
				codeSousMatiere: "",
				typeDevoir: "Devoir sur table",
				enLettre: false,
				coef: "1",
				noteSur: "20",
				valeur: "18,7",
				nonSignificatif: false,
				date: "2021-09-24",
				dateSaisie: "2021-09-24",
				valeurisee: false,
				moyenneClasse: "14.46",
				minClasse: "9.30",
				maxClasse: "18.70",
				elementsProgramme: [],
			},
			{
				devoir: "Contrôle",
				codePeriode: "A001",
				codeMatiere: "FRANC",
				libelleMatiere: "FRANCAIS",
				codeSousMatiere: "",
				typeDevoir: "Devoir sur table",
				enLettre: false,
				coef: "3",
				noteSur: "20",
				valeur: "15",
				nonSignificatif: false,
				date: "2021-09-28",
				dateSaisie: "2021-09-28",
				valeurisee: false,
				moyenneClasse: "12.26",
				minClasse: "7.00",
				maxClasse: "17.00",
				elementsProgramme: [],
			},
			{
				devoir: "Analyse de Doc Histoire",
				codePeriode: "A001",
				codeMatiere: "HI-GE",
				libelleMatiere: "HISTOIRE-GEOGRAPHIE",
				codeSousMatiere: "",
				typeDevoir: "",
				enLettre: false,
				coef: "2",
				noteSur: "20",
				valeur: "11",
				nonSignificatif: false,
				date: "2021-09-29",
				dateSaisie: "2021-10-14",
				valeurisee: false,
				moyenneClasse: "11.95",
				minClasse: "9.00",
				maxClasse: "15.00",
				elementsProgramme: [],
			},
			{
				devoir: "Eval 1",
				codePeriode: "A001",
				codeMatiere: "PH-CH",
				libelleMatiere: "PHYSIQUE-CHIMIE",
				codeSousMatiere: "",
				typeDevoir: "",
				enLettre: false,
				coef: "1",
				noteSur: "20",
				valeur: "20",
				nonSignificatif: false,
				date: "2021-09-30",
				dateSaisie: "2021-09-30",
				valeurisee: false,
				moyenneClasse: "19.00",
				minClasse: "13.00",
				maxClasse: "20.00",
				elementsProgramme: [],
			},
			{
				devoir: "TP Sept",
				codePeriode: "A001",
				codeMatiere: "PH-CH",
				libelleMatiere: "PHYSIQUE-CHIMIE",
				codeSousMatiere: "",
				typeDevoir: "",
				enLettre: false,
				coef: "1",
				noteSur: "20",
				valeur: "20",
				nonSignificatif: false,
				date: "2021-09-30",
				dateSaisie: "2021-09-30",
				valeurisee: false,
				moyenneClasse: "17.54",
				minClasse: "14.00",
				maxClasse: "20.00",
				elementsProgramme: [],
			},
			{
				devoir: "Devoir maison 1",
				codePeriode: "A001",
				codeMatiere: "MATHS",
				libelleMatiere: "MATHEMATIQUES",
				codeSousMatiere: "",
				typeDevoir: "",
				enLettre: false,
				coef: "0.5",
				noteSur: "20",
				valeur: "20",
				nonSignificatif: false,
				date: "2021-10-03",
				dateSaisie: "2021-10-03",
				valeurisee: false,
				moyenneClasse: "17.70",
				minClasse: "14.00",
				maxClasse: "20.00",
				elementsProgramme: [],
			},
			{
				devoir: "Contrôle 1",
				codePeriode: "A001",
				codeMatiere: "MATHS",
				libelleMatiere: "MATHEMATIQUES",
				codeSousMatiere: "",
				typeDevoir: "",
				enLettre: false,
				coef: "3",
				noteSur: "20",
				valeur: "18,5",
				nonSignificatif: false,
				date: "2021-10-05",
				dateSaisie: "2021-10-17",
				valeurisee: false,
				moyenneClasse: "13.48",
				minClasse: "7.00",
				maxClasse: "20.00",
				elementsProgramme: [],
			},
			{
				devoir: "Oral en continu sur les vacances",
				codePeriode: "A001",
				codeMatiere: "ALL2",
				libelleMatiere: "ALLEMAND",
				codeSousMatiere: "",
				typeDevoir: "",
				enLettre: false,
				coef: "2",
				noteSur: "20",
				valeur: "15",
				nonSignificatif: false,
				date: "2021-10-05",
				dateSaisie: "2021-10-05",
				valeurisee: false,
				moyenneClasse: "14.26",
				minClasse: "11.00",
				maxClasse: "20.00",
				elementsProgramme: [],
			},
			{
				devoir: "DM ",
				codePeriode: "A001",
				codeMatiere: "FRANC",
				libelleMatiere: "FRANCAIS",
				codeSousMatiere: "",
				typeDevoir: "Devoir Maison",
				enLettre: false,
				coef: "1",
				noteSur: "20",
				valeur: "20",
				nonSignificatif: false,
				date: "2021-10-06",
				dateSaisie: "2021-10-06",
				valeurisee: false,
				moyenneClasse: "13.15",
				minClasse: "4.00",
				maxClasse: "20.00",
				elementsProgramme: [],
			},
			{
				devoir: "Mini-projet html_css",
				codePeriode: "A001",
				codeMatiere: "NSINF",
				libelleMatiere: "NUMERIQUE SC.INFORM.",
				codeSousMatiere: "",
				typeDevoir: "Devoir sur table",
				enLettre: false,
				coef: "1",
				noteSur: "20",
				valeur: "19",
				nonSignificatif: false,
				date: "2021-10-07",
				dateSaisie: "2021-09-24",
				valeurisee: false,
				moyenneClasse: "14.88",
				minClasse: "9.00",
				maxClasse: "19.00",
				elementsProgramme: [],
			},
			{
				devoir: "CO",
				codePeriode: "A001",
				codeMatiere: "AGL",
				libelleMatiere: "ANGLAIS",
				codeSousMatiere: "",
				typeDevoir: "",
				enLettre: false,
				coef: "1",
				noteSur: "20",
				valeur: "15",
				nonSignificatif: false,
				date: "2021-10-11",
				dateSaisie: "2021-10-03",
				valeurisee: false,
				moyenneClasse: "13.57",
				minClasse: "6.00",
				maxClasse: "17.00",
				elementsProgramme: [],
			},
			{
				devoir: "PPO en binôme",
				codePeriode: "A001",
				codeMatiere: "HI-GE",
				libelleMatiere: "HISTOIRE-GEOGRAPHIE",
				codeSousMatiere: "",
				typeDevoir: "",
				enLettre: false,
				coef: "1",
				noteSur: "10",
				valeur: "9",
				nonSignificatif: false,
				date: "2021-10-13",
				dateSaisie: "2021-10-27",
				valeurisee: false,
				moyenneClasse: "7.68",
				minClasse: "5.50",
				maxClasse: "9.00",
				elementsProgramme: [],
			},
			{
				devoir: "Evaluation",
				codePeriode: "A001",
				codeMatiere: "G-SCI",
				libelleMatiere: "ENSEIGN.SCIENTIFIQUE",
				codeSousMatiere: "",
				typeDevoir: "Devoir sur table",
				enLettre: false,
				coef: "1",
				noteSur: "20",
				valeur: "18",
				nonSignificatif: false,
				date: "2021-10-14",
				dateSaisie: "2021-10-14",
				valeurisee: false,
				moyenneClasse: "15.33",
				minClasse: "8.00",
				maxClasse: "20.00",
				elementsProgramme: [],
				qcm: {
					idQCM: 167,
					idAssociation: 127,
					titre: "QCM 1ES - Matière (cristaux et cellules)",
					debute: "2021-10-14 10:27:50",
				},
			},
			{
				devoir: "CC 1",
				codePeriode: "A001",
				codeMatiere: "PH-CH",
				libelleMatiere: "PHYSIQUE-CHIMIE",
				codeSousMatiere: "",
				typeDevoir: "",
				enLettre: false,
				coef: "3",
				noteSur: "20",
				valeur: "10,5",
				nonSignificatif: false,
				date: "2021-10-18",
				dateSaisie: "2021-10-18",
				valeurisee: false,
				moyenneClasse: "10.54",
				minClasse: "2.00",
				maxClasse: "20.00",
				elementsProgramme: [],
			},
			{
				devoir: "DM ",
				codePeriode: "A001",
				codeMatiere: "FRANC",
				libelleMatiere: "FRANCAIS",
				codeSousMatiere: "",
				typeDevoir: "Devoir Maison",
				enLettre: false,
				coef: "1",
				noteSur: "20",
				valeur: "18",
				nonSignificatif: false,
				date: "2021-10-18",
				dateSaisie: "2021-10-18",
				valeurisee: false,
				moyenneClasse: "14.13",
				minClasse: "8.00",
				maxClasse: "19.00",
				elementsProgramme: [],
			},
			{
				devoir: "EE",
				codePeriode: "A001",
				codeMatiere: "AGL",
				libelleMatiere: "ANGLAIS",
				codeSousMatiere: "",
				typeDevoir: "",
				enLettre: false,
				coef: "2",
				noteSur: "20",
				valeur: "15",
				nonSignificatif: false,
				date: "2021-10-20",
				dateSaisie: "2021-10-08",
				valeurisee: false,
				moyenneClasse: "12.93",
				minClasse: "9.00",
				maxClasse: "17.00",
				elementsProgramme: [],
			},
			{
				devoir: "TP Fer III",
				codePeriode: "A001",
				codeMatiere: "PH-CH",
				libelleMatiere: "PHYSIQUE-CHIMIE",
				codeSousMatiere: "",
				typeDevoir: "",
				enLettre: false,
				coef: "1",
				noteSur: "20",
				valeur: "20",
				nonSignificatif: false,
				date: "2021-10-22",
				dateSaisie: "2021-10-21",
				valeurisee: false,
				moyenneClasse: "18.89",
				minClasse: "17.00",
				maxClasse: "20.00",
				elementsProgramme: [],
			},
		],
		parametrage: {
			couleurEval1: "#FF0000",
			couleurEval2: "#FFC000",
			couleurEval3: "#0070C0",
			couleurEval4: "#00B050",
			libelleEval1: "Tm9uIGF0dGVpbnRz",
			libelleEval2: "UGFydGllbGxlbWVudCBhdHRlaW50cw==",
			libelleEval3: "QXR0ZWludHM=",
			libelleEval4: "RMOpcGFzc8Opcw==",
			affichageMoyenne: false,
			affichageMoyenneDevoir: true,
			affichagePositionMatiere: false,
			affichageNote: true,
			affichageCompetence: false,
			affichageEvaluationsComposantes: false,
			affichageGraphiquesComposantes: true,
			modeCalculGraphiquesComposantes: "eval",
			affichageCompNum: false,
			libelleEvalCompNum1: "Tm9uIGF0dGVpbnQ=",
			libelleEvalCompNum2: "UGFydGllbGxlbWVudCBhdHRlaW50",
			libelleEvalCompNum3: "QXR0ZWludA==",
			affichageAppreciation: false,
			coefficientNote: true,
			colonneCoefficientMatiere: true,
			noteGrasSousMoyenne: true,
			noteGrasAudessusMoyenne: false,
			libelleDevoir: true,
			dateDevoir: true,
			typeDevoir: true,
			noteUniquementPeriodeCloture: false,
			notePeriodeReleve: false,
			notePeriodeAnnuelle: false,
			notePeriodeHorsP: false,
			libellesAppreciations: ["Appréciation générale"],
			appreciationsParametrage: [
				{
					code: "APP1",
					id: 1,
					nbMaxCaractere: 160,
					libelle: "Appréciation générale",
				},
			],
		},
	},
	firstSeenAt: "2021-10-29T13:46:21.007Z",
	lastSeenAt: "2021-11-03T10:42:34.623Z",
	dates: [
		"2021-10-29T13:46:21.007Z",
		"2021-10-29T14:00:10.295Z",
		"2021-10-30T13:54:34.622Z",
		"2021-11-02T12:15:48.721Z",
		"2021-11-02T12:15:49.706Z",
		"2021-11-02T17:43:35.060Z",
		"2021-11-03T10:05:01.241Z",
		"2021-11-03T10:42:34.623Z",
	],
	__v: 7,
};
console.log(removeDates(reviveDates(obj)));
